name: zakath_app
description: Islamic Zakath Calculator & Finance App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_riverpod: ^2.3.8
  riverpod: ^2.3.8
  flutter_secure_storage: ^8.0.5
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true